# mathematical operation on numpy arrays


In [1]:
import numpy as np

In [ ]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]

print(list1 + list2) #concatenate two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [4]:
arnd=np.random.randint(0,10,(3,3))
brnd=np.random.randint(10,20,(3,3))
print(arnd)
print()
print(brnd)

[[5 2 2]
 [4 3 3]
 [6 4 0]]

[[11 15 10]
 [17 17 13]
 [17 15 10]]


In [5]:
print("Addition of numpy array")
print(arnd + brnd)
print("subtraction")
print(arnd-brnd)
print("multiplication")
print(arnd*brnd)
print("division ")
print(arnd / brnd)

Addition of numpy array
[[16 17 12]
 [21 20 16]
 [23 19 10]]
subtraction
[[ -6 -13  -8]
 [-13 -14 -10]
 [-11 -11 -10]]
multiplication
[[ 55  30  20]
 [ 68  51  39]
 [102  60   0]]
division 
[[0.45454545 0.13333333 0.2       ]
 [0.23529412 0.17647059 0.23076923]
 [0.35294118 0.26666667 0.        ]]


In [7]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))


In [8]:
print(a)
print(b)

[[1 3 1]
 [7 7 3]
 [5 1 2]]
[[10 12 19]
 [12 16 13]
 [13 10 15]]


In [9]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[11 15 20]
 [19 23 16]
 [18 11 17]]
[[ -9  -9 -18]
 [ -5  -9 -10]
 [ -8  -9 -13]]
[[ 10  36  19]
 [ 84 112  39]
 [ 65  10  30]]
[[0.1        0.25       0.05263158]
 [0.58333333 0.4375     0.23076923]
 [0.38461538 0.1        0.13333333]]


ARRAY MANUPULATION 

In [10]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)
type(array)

[[8 5 2]
 [1 3 4]]
(2, 3)


numpy.ndarray

In [11]:
# transpose of matrix
trans=np.transpose(array)
print(trans)
print(trans.shape)

[[8 1]
 [5 3]
 [2 4]]
(3, 2)


In [12]:
trans2=array.T
print(trans2)
print(trans2.shape)

[[8 1]
 [5 3]
 [2 4]]
(3, 2)


In [18]:
#reshaping array
aa=np.random.randint(0,10,(2,3))
print(aa)
print(aa.shape)

[[6 8 4]
 [8 1 8]]
(2, 3)


In [19]:
bb=aa.reshape(3,2)
print(bb)

[[6 8]
 [4 8]
 [1 8]]
