# Numpy --> numerical python

Advantages of numpy Arrays :


  1.Allow several mathematical operations
 

 2.Faster operations

In [38]:
import numpy as np

numpy arrays


In [39]:
#list 
list1= [1,2,3,4,5,6]
print(list1)
type(list1)

[1, 2, 3, 4, 5, 6]


list

In [40]:
# numpy arrays
np_array=np.array([1,2,3,4,5,6])
print(np_array)
type(np_array)


[1 2 3 4 5 6]


numpy.ndarray

In [41]:
# 1d array
a=np.array([1,2,3,4,5])
print(a)
a.shape

[1 2 3 4 5]


(5,)

In [42]:
#2d array
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [43]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


initial placeholders in numpy arrays

In [44]:
#creating a numpy arrays of 0s
arr0s=np.zeros((3,4))
print(arr0s)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [45]:
#creating a numpy array of particular value
particular=np.full((4,5),8)
print(particular)


[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]


In [46]:
#creating a numpy arrays of 1s
arr1s=np.ones((4,4))
print(arr1s)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [47]:
#creating identity matrix 
eye=np.eye(4)
print(eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [48]:
#creating a numpy array of random numbers
arrRandom=np.random.random((4,5))
print(arrRandom)

[[0.06170933 0.3486661  0.25753808 0.10047935 0.94867323]
 [0.30486329 0.83224297 0.43526799 0.7533912  0.04545654]
 [0.60592103 0.90603747 0.32776637 0.74455009 0.13805296]
 [0.44639683 0.83160644 0.32231318 0.23503604 0.05986063]]


In [49]:
# creating an numpy array with random no. but specific range
a=np.random.randint(10,110,(3,6))
print(a)

[[ 49  15  70  69 109  32]
 [104  34  64  28  45  97]
 [ 16  89  62  30  62  40]]


In [50]:
#array of evenly spaced values --> specifying the number of values required
n=np.linspace(10,30,5)
print(n)


[10. 15. 20. 25. 30.]


In [51]:
# array of evenly spaced values--> specifying the no of steps
ne=np.arange(10,30,5)
print(ne)

[10 15 20 25]


# convert a list to nampy array

In [52]:
list2=[10,20,30,30,50]
np_array=np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 30 50]


numpy.ndarray

# analysing numpy arrays

In [53]:
np=np.random.randint(10,90,(4,5))
print(np)

[[30 24 55 47 88]
 [16 23 73 67 83]
 [84 70 68 31 25]
 [43 48 56 78 10]]


In [54]:
# array dimension
np.shape

(4, 5)

In [55]:
#number of dimension

print(np.ndim) 

2


In [56]:
#number od elements in an array
print(np.size)

20


In [57]:
# checking the datatypes of the values of an array
print(np.dtype)

int32
